server:
  port: 8082
  servlet:
    context-path: /DataClassification
    
    
spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 1MB
      max-file-size: 200MB
      max-request-size: 215MB

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3307/data_classification
    username: client
    password: client
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update